inherit_from: .rubocop_todo.yml

AllCops:
  Includes:
    - Rakefile
    - config.ru
    - '**/*.rb'
  Excludes:
    - db/
    - config/
    - script/
    - vendor//*
    - bin/* # Circle adds the rubies here
    - db/schema.rb