default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: 
  pool: 5

production:
  <<: *default
  database: <nombre de tu app>_production

development:
  <<: *default
  database: <nombre de tu app>_development

test:
  <<: *default
  database: <nombre de tu app>_test
